# .github/FUNDING.yml

patreon: bkader
ko_fi: bkader
liberapay: bkader
buy_me_a_coffee: bkader
custom: [
  "https://donatr.ee/bkader",
  "https://www.paypal.com/ncp/payment/YV45BR3J6HH94"
]
